# Generated by Django 5.1.7 on 2025-03-08 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=64)),
                ("image_link", models.SlugField()),
                ("language", models.CharField(max_length=64)),
                ("link", models.SlugField()),
                ("pages", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=64)),
                ("year", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
